### ISSUE TITLE
Can you give a simple example of a simple call to .net core?

### ISSUE THREAD

**Issue by qibunext** [paypal/Checkout-NET-SDK#19]
Can you give a simple example of a simple call to .net core? I really don't know how to use it.

~~~
c#
System.AggregateException: One or more errors occurred. ({"error":"invalid_client","error_description":"Client Authentication failed"}) ---> BraintreeHttp.HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"}
   at BraintreeHttp.HttpClient.Execute(HttpRequest request)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PayPalCheckoutSdk.Core.PayPalHttpClient.AuthorizationInjector.Inject(HttpRequest request)
   at BraintreeHttp.HttpClient.Execute(HttpRequest request)
   at Qibu.Controllers.PayPalExpressController.Approval(String OrderNO, String Total, String description)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
---> (Inner Exception #0) BraintreeHttp.HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"}
   at BraintreeHttp.HttpClient.Execute(HttpRequest request)<---


~~~

**Comment by tiffanyrzhou** [comment]
Thanks for reaching out. The samples provided in the repo is using .net core 2.0. 

The error you are seeing is due to invalid credentials. You can generate a set of sandbox credentials by logging in to your PayPal developer dashboard.

A simple way of changing these credential would be adding them to the [Samples/PayPalClient.cs](https://github.com/paypal/Checkout-NET-SDK/blob/develop/Samples/PayPalClient.cs) file.

I would recommend taking a look at the [RunAllCaptureIntent.cs](https://github.com/paypal/Checkout-NET-SDK/blob/develop/Samples/CaptureIntentExamples/RunAllCaptureIntentFlow.cs) file.
